!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.0)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitextrapolate(f2pysetupfunc)
      use extrapolate, only : fill
      external f2pysetupfunc
      call f2pysetupfunc(fill)
      end subroutine f2pyinitextrapolate


