[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python >=0.16.0",
    "numpy >= 2.0.2",
]

[project]
name = "interpolate"
version = "0.1.0"
requires-python = ">= 3.11.10"
dependencies = [
    "numpy >= 2.0.2",
]

