default:
  output_dir: /home/otel/Desktop/deletar/pyroms_tests
  bathy_file: /mnt/34c919f6-6617-49de-a20f-05e4186230b9/Dropbox/trabalho_irado/2022/postdoc/202203_ceresIV/pyroms_tools_new/data/raw/gebco.nc
  grid:
    dxdy: 0.125
    xoffset: 3.5
    yoffset: 2
    WESN: [-57, -45.4, -42, -17.5]
    rot: -0.9
    N: 40
    theta_s: 6
    theta_b: 2
    Tcline: 100
    grid: /home/otel/Desktop/deletar/pyroms_tests/roms_grid01_2.012.nc
  smooth:
    input: /home/otel/Desktop/deletar/pyroms_tests/roms_grid01_2.012.nc
    output: /home/otel/Desktop/deletar/pyroms_tests/roms_grid01_2.012_smooth.nc
    capdepth: 5000
    smooth: 0.125
    nested: False
    inputaux: ''